---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

Meghan Harri's blog: https://www.thetidytrekker.com/post/thinking-outside-the-grid

Para hacer un cuadrado:

```{r}
knitr::opts_chunk$set(
  fig.path = "images/"
)
library(tidyverse)
cuadrado <- tibble(x = c(1,9,9,1),
                   y = c(1,1,9,9))
```

Para armar un cuadrado, de forma tal que cierre la figura, se debe usar `geom_polygon()`, porque esta función conecta automáticamente los puntos para que se complete la forma:

```{r}
cuadrado %>% 
  ggplot(aes(x = x, y = y))+
  geom_polygon(fill = "red")
```

```{r}
hexagono <- tibble(x= c(0,2,4,6,4,2),
                   y=c(2,0,0,2,4,4))

hexagono %>% 
  ggplot(aes(x = x, y = y))+
  geom_polygon(fill = "red")

cruzado <- tibble(x=c(0, 4,7,10,16,19,22,16,13,10,4,1),
                  y=c(0,0,-3,0,0,-3,0,0,3,0,0,3))

cruzado %>% 
  ggplot(aes(x = x, y = y))+
  geom_polygon(fill = "lightseagreen")+
  geom_point(color = "mediumpurple3")
```

Dataframe con puntos randomizados (solo en eje y)
```{r}
random_points <- tibble(x = 1:1000,
                        y = sample(1:1000))

random_points %>% 
  ggplot(aes(x=x, y=y))+
  geom_point()

estrellas <- c("#FFFFFF","#FCF7E1","#FAEFC3","#F7E6A5","#F4DE87","#F1D669","#EFCE4B","#ECC52D","#E9BD0F")

# con colores randomizados:
random_points %>% 
  ggplot(aes(x=x, y=y))+
  geom_point(color = sample(estrellas, nrow(random_points), replace = TRUE), 
             size = sample(0.01:1.10, nrow(random_points), replace = TRUE),
             shape = 8,
             alpha = 0.7)+
  labs(x = "",y="")+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.background = element_blank(),
        panel.background = element_rect(fill = "black"),
        panel.grid = element_blank())
```

# Layering

```{r}
cruzado <- tibble(x=c(0, 4,7,10,16,19,22,16,13,10,4,1),
                  y=c(0,0,-3,0,0,-3,0,0,3,0,0,3))

cruzado %>% 
  ggplot(aes(x = x, y = y))+
  geom_polygon(fill = "lightseagreen")+
  geom_point(color = "mediumpurple3")+
  geom_point(data = puntos, aes(x=x, y=y, 
                                size = sample(0:1.5, nrow(puntos),
                                              replace = TRUE)), 
             inherit.aes = FALSE)+
  theme(legend.position = "none")

puntos <- tibble(x = c(2.5, 7.5, 12.5, 18),
                 y = c(-1.9, 2, -1.9, 2))
```

